name: GitHub Actions Job Summary
description: It generates GitHub Actions Job Summary with Markdown file.
author: x-color
inputs:
  file:
    required: true
  vars:
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  color: green
  icon: file-text
